//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BABULESASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaction
    {
        public int Id { get; set; }
        public string tr_categorie { get; set; }
        public string tr_type { get; set; }
        public Nullable<decimal> tr_sum { get; set; }
        public Nullable<System.DateTime> tr_date { get; set; }
        public string tr_description_ { get; set; }
    }
}
